### ISSUE TITLE
loadPrismaData Error

### ISSUE THREAD

**Issue by valour01** [hgascon/pulsar#1]
I am going to use pulsar to learn a model with pcap file. I have a test.pcap in the dir of pulsar and when I am going to `python pulsar.py -l -p test.pcap`
The below exception raised:

> source("prisma.R")
> source("dimensionEstimation.R")
> source("matrixFactorization.R") 
> setwd(initial_dir)
> 
>  load the dataset
> print(capture_dir)
> [1] "/usr/local/src/pulsar/models/test/test"
> data = loadPrismaData(capture_dir)
> Reading data...
> Splitting ngrams...
> Calc indices...
> Setup matrix...
> to check: 2 
> Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
>   index larger than maximal 0
> Calls: loadPrismaData ... callGeneric -> eval -> eval -> [ -> [ -> subCsp_rows -> intI
> Execution halted
> Traceback (most recent call last):
>   File "pulsar.py", line 97, in <module>
>     mg.generate_model()
>   File "/usr/local/src/pulsar/pulsar/core/model.py", line 59, in generate_model
>     self._generate_model_pcaps()
>   File "/usr/local/src/pulsar/pulsar/core/model.py", line 78, in _generate_model_pcaps
>     self._build_model_files(pcap_noext)
>   File "/usr/local/src/pulsar/pulsar/core/model.py", line 185, in _build_model_files
>     urllib.unquote(self.whitespace), self.subrules)
>   File "/usr/local/src/pulsar/pulsar/core/model.py", line 227, in __init__
>     self.dh = data.DataHandler(datapath, ngram, whitespace)
>   File "/usr/local/src/pulsar/pulsar/core/data.py", line 19, in **init**
>     self._readClusterAssignments()
>   File "/usr/local/src/pulsar/pulsar/core/data.py", line 35, in _readClusterAssignments
>     self.N, skipFirstLine=False)
>   File "/usr/local/src/pulsar/pulsar/core/data.py", line 78, in _processData
>     f = file(fname, "r")
> IOError: [Errno 2] No such file or directory: '/usr/local/src/pulsar/models/test/test.cluster'

I noticed the code crash in `curCor = sparse.cor(mat[toCheck, ])`. I noticed that you are also the author of PRISMA. I am wondering whether this problem is related to my pcap file or if you need more information. Many Thanks. And it would also be great if you can share your test data

**Comment by hgascon** [comment]
Are derrick files and prisma input files generated correctly? What files are generated in "/usr/local/src/pulsar/models/test/test"? Can you provide an example pcap?  If everything is correct, then the issue might be in PRISMA (https://github.com/tammok/PRISMA/issues/2)

**Comment by valour01** [comment]
Sorry for the late response. There are `test.drk  test.fdrk  test.fsally  test.harry  test.pcap  test.raw  test.rawquoted  test.sally` inside the directory. And the example pcap are [here](https://github.com/valour01/Pulsar_test/blob/master/test.pcap)

**Comment by hgascon** [comment]
The PRISMA input files seem to be generated correctly. Let's see if @tammok can share some light about the error.

**Comment by valour01** [comment]
okay, thanks for your help. Hope tommok can give me some hints. Many thanks

**Comment by hgascon** [comment]
I checked your pcaps files with more detail and have some comments:
- A model is built on a IP Address:port basis. That means that each pcap should contain only traffic from a communication channel (one source IP1:PORT1 and one destination IP2:PORT2).
- If the communication is encrypted (as is the case for some of the files), it won't be possible to infer anything from the traffic.
- If there are not enough packets from the client and the server, it won't be possible to build a model. This means that an HTTP request and a response are not sufficient. The ideal use case is a relatively large pcap from an unknown protocol (text based or binary) with similar traffic rates for the client and the server.

**Comment by valour01** [comment]
Thanks @hgascon. I agree with you. I will going to have to try first. Many Thanks.

**Comment by valour01** [comment]
@hgascon  I guess the following might be bugs, please have a check. Many Thanks
- The init method of Simulator is `__init__(self, model_path):` while you pass `Simulator(os.path.realpath(args.model), path_conf)`
- In the row 718 of `lens.py`, I think you need to have a check that `len(dst_fields)>dst` because I come up with  the following exception which means index out.
  
  > Traceback (most recent call last):
  >   File "pulsar.py", line 116, in <module>
  >     f.run()
  >   File "/usr/local/src/pulsar/pulsar/core/fuzzer.py", line 112, in run
  >     snd_message = self.lens.transitionSelf()
  >   File "/usr/local/src/pulsar/pulsar/core/lens.py", line 897, in transitionSelf
  >     return self.transition(self.role, True)
  >   File "/usr/local/src/pulsar/pulsar/core/lens.py", line 994, in transition
  >     (state, template, msg, fields, transition) = self._transition_to_state(next_state)
  >   File "/usr/local/src/pulsar/pulsar/core/lens.py", line 1040, in _transition_to_state
  >     self.fuzzer)
  >   File "/usr/local/src/pulsar/pulsar/core/lens.py", line 719, in create_fuzzed_message
  >     if dst_fields[dst] == data:
  > KeyError: 0
- When `>>> CHECKING FOR TERMINATED EXECUTION` the below exception raised:
  
  >  File "pulsar.py", line 116, in <module>
  > f.run()
  > File "/usr/local/src/pulsar/pulsar/core/fuzzer.py", line 134, in run
  >   self._termination_check()
  > File "/usr/local/src/pulsar/pulsar/core/fuzzer.py", line 262, in _termination_check
  >   task = self.db.view_task(self.task_id)
  > AttributeError: Fuzzer instance has no attribute 'task_id'

**Comment by hgascon** [comment]
I checked the three issues and added certain fixes. Let me know how it goes.

**Comment by leesangmin144** [comment]
Hi hgascon! I have a similar Exception too. 
pcap file was made up only HTTP protocol (simple Request, Response) and i executed "# python pulsar.py -l -p test.pcap". used pcap file is [this](https://github.com/leesangmin144/pulsar/blob/master/test.pcap). As results, generated 8 files(test.drk  test.fdrk  test.fsally  test.harry  test.pcap  test.raw  test.rawquoted  test.sally) in "/home/pulsar/models/test" folder.

## The below Exception raised:

> source("prisma.R")
> source("dimensionEstimation.R")
> source("matrixFactorization.R") 
> setwd(initial_dir)
> 
> data = loadPrismaData(capture_dir)
> Reading data...
> Splitting ngrams...
> Calc indices...
> Setup matrix...
> Error in rep(1:N, sapply(ngrams[-total], length)) : 
>   invalid 'times' argument
> Calls: loadPrismaData -> readPrismaInput -> readFSally -> sparseMatrix
> Execution halted
> Error during clustering (not enough data?)
> Cluster file not generated: /home/pulsar/models/test/test.cluster
> Exiting learning module...

---

I would appreciate your attention.

**Comment by hgascon** [comment]
Hi @leesangmin144, with pulsar you can model a single channel between a source IP:PORT and a destination IP:PORT.  In test.pcap you have many sessions with different end points.

Try, for example, to generate a pcap with the traffic between 192.168.10.4:50273 and 110.45.229.135:80 (wireshark filter ip.addr==192.168.10.4 && tcp.port==50273 && ip.addr==110.45.229.135 && tcp.port==80). This is the channel with the most traffic in your pcap file.

**Comment by leesangmin144** [comment]
Thank you for answer hgascon. I solving this matter.
I generate new single channel packet because your recommend traffic data in my test.pcap is insufficient for clustering. [this](https://github.com/leesangmin144/pulsar/blob/master/new_test.pcap) pcap file is made up single channel that a source IP:PORT and a destination IP:PORT and made up only HTTP Request/Response between simple Web Server and Client. Also, sufficient for clustering. 
Excuse me, can I ask you another question? Does PULSAR work unknown protocol better than proprietary protocol(http,...)?

**Comment by hgascon** [comment]
I am not sure I understand your question. Pulsar can model any protocol, proprietary or not, known or unknown. The tool uses statistical methods to approximate the protocol, so its model will never be as precise as the real specification of a standard protocol in the case that it exists. Such is the case for HTTP.

**Comment by leesangmin144** [comment]
There is a part that is not understood well because it is a non-English speaking country. But, thanks for your reply. I understand it well. :)
