### ISSUE TITLE
Native SSL/TLS Support

### ISSUE THREAD

**Issue by Himself132** [hgascon/pulsar#19]
Hello,

Really interested in trying this tool out, but i was wondering if there were ever any plans to do protocols inside SSL/TLS? or SSL/TLS protocols like TLS 1.3?

**Comment by hgascon** [comment]
There were not. I guess it could be used in combination with something like https://mitmproxy.org/ to inspect and model the underlying protocol. If used directly on TLS, it should be possible to model the handshake but not the encrypted traffic.
