### ISSUE TITLE
“Error during clustering (not enough data?)”

### ISSUE THREAD

**Issue by Aaron911** [hgascon/pulsar#24]
hi, hgason. When I ran" python pulsar.py -l -p 11.pcap", I got the error “Error during clustering (not enough data?)”. My output is as follows：
`~/pulsar$ python pulsar.py -l -p 11.pcap

                 _
     _ __  _   _| |___  __ _ _ __
    | '_ \| | | | / __|/ _` | '__|
    | |_) | |_| | \__ \ (_| | |
    | .__/ \__,_|_|___/\__,_|_|  v0.1-dev
    |_|
        
>>> Creating dir /home/wx/pulsar/models/11
>>> Extracting DERRICK files from 11
>>> Generating PRISMA input files from 11
>>> Clustering data...
sh: 1: R: not found
Error during clustering (not enough data?)
Cluster file not generated: /home/wx/pulsar/models/11/11.cluster
Exiting learning module...
`
My pcap file only includes the packages corresponding to a connection between a client and a server at specific ports. And I have tried the pcap file in the link of https://github.com/hgascon/pulsar/issues/7#issue-277569981 , but I also get the same error. I dont know which step I did wrong. Looking forward to your reply.

**Comment by GilgameshC** [comment]
You need to install R environment first

**Comment by Aaron911** [comment]
> You need to install R environment first

ohhhhh! Thank u! I should have read the log carefully.
