### ISSUE TITLE
Err: No active connection to close

### ISSUE THREAD

**Issue by EmiPali** [hgascon/pulsar#26]
I tried to simulate a connection based on a given model I generated before and I got the following error which is shown in the image as well: 
Err: set the Simulator role to 'client'                    or 'server' in /home/emi/pulsar/test
I went to fuzzer.py in conf directory and changed the role from client to server and the other way around but I am still getting the same error.
When I try to use the same model for starting a fuzzing session I get : 
socket.error: [Errno 110] Connection timed out.
Can you please help me? 
![Screenshot from 2021-02-22 09-17-15](https://user-images.githubusercontent.com/56865035/108681424-6bd41900-74ef-11eb-9f28-ff72eab83208.png)
![Screenshot from 2021-02-22 09-17-23](https://user-images.githubusercontent.com/56865035/108681428-6c6caf80-74ef-11eb-85e5-8ca8b566ecd7.png)

**Comment by hgascon** [comment]
How does your model look like? Was it generated correctly?

**Comment by EmiPali** [comment]
Yes, the model was generated correctly I checked. And I tried to generate again another one and I figured that the problem was that I had opened the server in UDP mode and I needed in tcp mode. 
![send](https://user-images.githubusercontent.com/56865035/110005171-7b860580-7d18-11eb-8d21-b99cfb10685d.png)
This is what I got when I ran python pulsar.py -z -m modelname.
1. What it wrong in the result i got above?
2. Can I relearn a model and make it use udp?

**Comment by hgascon** [comment]
1. It looks like your service being fuzzed crashed and the prisma module threw an exception when the communication broke. Are you running the other service in the same terminal?
2. Yes, you can learn from pcaps containing UDP communication.
