### ISSUE TITLE
Bug in filter.py?

### ISSUE THREAD

**Issue by tg-mw** [hgascon/pulsar#27]
I was testing pulsar with PCAP files containing DNS traffic and discovered that the resulting markov model was incorrect, as it only contained "START|X.UAC" states and no "X.UAS", even though DNS responses were also captured. In the .harry file, there were also only UAC entries which are mapped to the actual DNS responses:

```
dialogId        msgNumber       origin  type
0       0       UAC     1%ea%81%83%00%01 ...
1       0       UAC     %f5%0d%81%83%00%01 ...
2       0       UAC     %0c%a9%81%80%00%01 ...
3       0       UAC     %9d%e6%81%80%00%01 ...
4       0       UAC     %a5k%81%80%00%01 ...
5       0       UAC     p%06%81%80%00%01%00 ...
6       0       UAC     %edM%81%80%00%01%00%00 .. 
7       0       UAC     K%bb%81%80%00%01%00%02% ...
8       0       UAC     %db(%81%83%00%01%00%00%00 ...
```

However, after changing

```
for (k, msg) in src_dst_dic.iteritems():
    if response[k] == 0:
        mergedMessages.append(msg)
mergedMessages.sort(key=lambda m: m.ntime)
```

in `singlePassCheck()` in filter.py to

```
for (k, msg) in src_dst_dic.iteritems():
    mergedMessages.append(msg)
mergedMessages.sort(key=lambda m: m.ntime)
```

it seems to work, the .harry file also contains the UAS entries and the corresponding packets are mapped correctly. However, I don't known if this change breaks something, i.e. when using TCP. Is there some configuration option that needs to be set when using UDP?

**Comment by hgascon** [comment]
Have you done a test with a TCP capture?

**Comment by tg-mw** [comment]
Thank you for your answer. The initial test was DNS over UDP. I generated new samples containing DNS over TCP and there seems to be a similar problem, even though the responses are sometimes displayed correctly:

```
dialogId        msgNumber       origin  type
0       0       UAC     %00:%9f%83%01
0       1       UAC     NONE
1       0       UAC     %008%9f%eb%01
1       1       UAS     %00`%9f%eb%81%83%00%01%00%00%00%01%00%01 [...]
1       2       UAC     NONE
2       0       UAC     %009%d8%0e%01
2       1       UAC     NONE
[...]
```

With the aforementioned change, the .harry file contains:

```
dialogId        msgNumber       origin  type
0       0       UAC     %00:%9f%83%01
0       1       UAS     %00b%9f%83%81%83%00%01%00%00%00%01%00 [...]
0       2       UAC     NONE
1       0       UAC     %008%9f%eb%01
1       1       UAS     %00`%9f%eb%81%83%00%01%00%00%00%01%00 [...]
1       2       UAC     NONE
2       0       UAC     %009%d8%0e%01
2       1       UAS     %00=%d8%0e%81%80%00%01%00%01%00%00%00 [...]
2       2       UAC     NONE
[...]
```

Here, each dialogId has an UAC and UAS entry and the markovModel seems to be correct. Does it work for you without the modification?

**Comment by hgascon** [comment]
I had not seen this problem so far. Could it be an issue with the `step` parameter in [pulsar/pulsar/conf/harry.conf](https://github.com/hgascon/pulsar/blob/master/pulsar/conf/harry.conf)? The default value is set to 10ms.
