### ISSUE TITLE
Error in 1:ncol(data) : argument of length 0

### ISSUE THREAD

**Issue by muginekoo** [hgascon/pulsar#29]
I am going to use pulsar to learn a model with pcap file. I have a test2.pcap in the dir of pulsar and when I am going to python pulsar.py -l -p test2.pcap
The below exception raised:
> source("prisma.R")
> source("dimensionEstimation.R")
> source("matrixFactorization.R") 
> setwd(initial_dir)
> 
> load the dataset
> data = loadPrismaData(capture_dir)
> data = loadPrismaData(capture_dir, skipFeatureCorrelation=TRUE)
Reading data...
Splitting ngrams...
Calc indices...
Setup matrix...
Error in 1:ncol(data) : argument of length 0
Calls: loadPrismaData ... preprocessPrismaData -> duplicateRemover -> sapply -> lapply
Execution halted
Error during clustering (not enough data?)
Cluster file not generated: /home/mjy/pulsar/models/test2/test2.cluster
Exiting learning module...

And the test pcap are [here](https://github.com/Benmolly/ntp.git).

**Comment by hgascon** [comment]
Are intermediate files created? There seem to be a problem with the prisma module.

**Comment by muginekoo** [comment]
> 

Some intermediate files were creared.  I tried to use different pcap files and seemed to solve it. (I guess there may not be enough information in the previous file.)
