### ISSUE TITLE
[Question] Hidden Markov Models

### ISSUE THREAD

**Issue by anneborcherding** [hgascon/pulsar#30]
Hi everyone,

I have a quick question regarding the models used in the code.

The Readme states:
> The tool allows to model a protocol through machine learning techniques, such as clustering and hidden Markov models.

In the code, I found Markov chains but no traces of Hidden Markov Models. Is the statement in the Readme to be understood more generally (as in "you could use the code to generate hidden markov models") or are hidden markov models actually generated by Pulsar?

Thanks in advance!

**Comment by hgascon** [comment]
You are right, a Markov chain is used to model the protocol state machine. I will update the readme to reflect that. You can read more details about it in section 2.4 of the original Prisma paper here: https://hugogascon.com/publications/2012a-aisec.pdf
