### ISSUE TITLE
source("prisma.R") error

### ISSUE THREAD

**Issue by IMhappyZzz** [hgascon/pulsar#4]
I am going to use pulsar to learn a model with pcap file. I have a test.pcap in the dir of pulsar and when I am going to python pulsar.py -l -p test.pcap
The below exception raised:
> 
> # store the current directory
> initial_dir<-getwd()
> 
> # load necessary libraries
> # library(PRISMA)
> library(Matrix)
> 
> # change to prisma src dir and load scripts
> setwd(prisma_dir) 
> source("prisma.R")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'prisma.R': No such file or directory
Execution halted
Error during clustering (not enough data?)
Cluster file not generated: /usr/local/src/pulsar-master/models/test/test.cluster
Exiting learning module...

I find the following codes will cause error: 
source("prisma.R")
source("dimensionEstimation.R")
source("matrixFactorization.R") 

I just installed prisma from R, I can't find the three ".R" files,How can I solve these problems?Thanks!

**Comment by hgascon** [comment]
you need to install https://github.com/tammok/PRISMA in the modules dir
