### ISSUE TITLE
test error?

### ISSUE THREAD

**Issue by xiaoyanguoke** [hgascon/pulsar#5]
I build in Windows Core FTP LE, then set up VSFTPD services under Linux, both can communicate, then I grabbed the FTP data packets, and stored in the pulsar directory and name for ftp. pcap, then I want to study to generate a model automatically, appear the following error。
![image](https://user-images.githubusercontent.com/15224735/28257161-1bc4ca42-6afb-11e7-95e5-9571c3c3da7e.png)

**Comment by stuartly** [comment]
It will be OK when setting the correct dir of PRISMA at the function of **setwd(prism_dir)**  in /pulsar/pulsar/core/cluster_generator.R.

>  change to prisma src dir and load scripts
 18 #setwd(prisma_dir)
 19 setwd("/home/pulsar/dependence/PRISMA/R")                                                                        
 20 source("prisma.R")
 21 source("dimensionEstimation.R")
 22 source("matrixFactorization.R") 
 23 setwd(initial_dir)

**Comment by xiaoyanguoke** [comment]
thanks

**Comment by hgascon** [comment]
@xiaoyanguoke did u solve that?

**Comment by xiaoyanguoke** [comment]
@hgascon I don't solve this problem,  @stuartly you solve this problem?

**Comment by stuartly** [comment]
@xiaoyanguoke @hgascon 
Yes, just as what I write in my comment on Jul 20. 

18 #setwd(prisma_dir)
19 setwd("/home/pulsar/dependence/PRISMA/R")
