### ISSUE TITLE
Problem when running pulsar in fuzzing mode

### ISSUE THREAD

**Issue by mlucas300** [hgascon/pulsar#7]
Pulsar looks like a really useful tool and I'm very keen to get it up and running as I haven't found anything else that is such a good match for what we require. I can run it in training mode and it runs as expected, but when I run it in fuzzing mode it terminates with an error. 

I have verified the issue with two different pcap files: one downloaded from https://download.netresec.com/pcap/4sics-2015/4SICS-GeekLounge-151022.pcap and another that I captured from local traffic. The error is (with some added debug print statements, which offset some of the lines in the stack trace from the actual line numbers in the unaltered code):

                _
     _ __  _   _| |___  __ _ _ __
    | '_ \| | | | / __|/ _` | '__|
    | |_) | |_| | \__ \ (_| | |
    | .__/ \__,_|_|___/\__,_|_|  v0.1-dev
    |_|
        
>>> RESETING MODEL...
host=192.168.56.101 port=9999

[*] Connected to server...
>>> Selecting next state in OFS mode...
State selected: ('START|None.UAC', 8180)
Probability-based selection from templates: ['353', '354', '355', '356', '357', '358', '362', '364', '365', '366', '367', '368', '369', '370', '371', '372', '373', '374', '376', '378', '379', '381', '382', '384']

fields_len=3 # Documents/Fuzzers/pulsar/pulsar/core/fuzzer.py:338

fuzz_mask_int=7 # Documents/Fuzzers/pulsar/pulsar/core/fuzzer.py:339

num=[-8] # /usr/lib/python2.7/dist-packages/numpy/core/numeric.py:2259

Traceback (most recent call last):
  File "./pulsar.py", line 115, in <module>
    f.run()
  File "Documents/Fuzzers/pulsar/pulsar/core/fuzzer.py", line 113, in run
    snd_message = self.lens.transitionSelf()
  File "Documents/Fuzzers/pulsar/pulsar/core/lens.py", line 895, in transitionSelf
    return self.transition(self.role, True)
  File "Documents/Fuzzers/pulsar/pulsar/core/lens.py", line 991, in transition
    (state, template, msg, fields, transition) = self._transition_to_state(next_state)
  File "Documents/Fuzzers/pulsar/pulsar/core/lens.py", line 1037, in _transition_to_state
    self.fuzzer)
  File "Documents/Fuzzers/pulsar/pulsar/core/lens.py", line 656, in create_fuzzed_message
    fuzz_fields = fuzzer.get_fuzz_fields(next_template.ID)
  File "Documents/Fuzzers/pulsar/pulsar/core/fuzzer.py", line 341, in get_fuzz_fields
    fields_len)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 2260, in binary_repr
    poswidth = len(bin(-num)[2:])
TypeError: only integer scalar arrays can be converted to a scalar index

I don't think it would be a fruitful exercise for me to try and debug it, so I was wondering if anyone else had come across this particular error.

I am running it on Debian 4.13.4-2kali1 (kali-rolling 2017.2)

Thanks,
Martin.

**Comment by hgascon** [comment]
Hi @mlucas300, that should be solved now. Let me know if you find any other issue and feel free to submit a pull request.
