### ISSUE TITLE
Unable to run learning mode 

### ISSUE THREAD

**Issue by akibsayyed** [hgascon/pulsar#8]
Dear Hugo

I am trying to run your app in learning mode for fuzzing. but facing issue. here is output of application run.

server:~/pulsar# ./pulsar.py -l -p tcap_fuzzing.pcap

                 _
     _ __  _   _| |___  __ _ _ __
    | '_ \| | | | / __|/ _` | '__|
    | |_) | |_| | \__ \ (_| | |
    | .__/ \__,_|_|___/\__,_|_|  v0.1-dev
    |_|

>>> Extracting DERRICK files from tcap_fuzzing
>>> Generating PRISMA input files from tcap_fuzzing
>>> Clustering data...

R version 3.0.2 (2013-09-25) -- "Frisbee Sailing"
Copyright (C) 2013 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

>
> # reading arguments
> cmd_args<- commandArgs(TRUE)
> prisma_dir<-cmd_args[1]
> capture_dir<-cmd_args[2]
> clusters_file<-cmd_args[3]
> nmf_ncomp<-cmd_args[4]
> print(cmd_args)
[1] "modules/PRISMA/R"
[2] "/root/pulsar/models/tcap_fuzzing/tcap_fuzzing"
[3] "/root/pulsar/models/tcap_fuzzing/tcap_fuzzing.cluster"
[4] "0"
>
> # store the current directory
> initial_dir<-getwd()
>
> # load necessary libraries
> # library(PRISMA)
> library(Matrix)
>
> # change to prisma src dir and load scripts
> setwd(prisma_dir)
Error in setwd(prisma_dir) : cannot change working directory
Execution halted
Error during clustering (not enough data?)
Cluster file not generated: /root/pulsar/models/tcap_fuzzing/tcap_fuzzing.cluster
Exiting learning module...
server:~/pulsar#

**Comment by hgascon** [comment]
Have you cloned the http://github.com/tammok/prisma repository in the `modules` dir?

**Comment by akibsayyed** [comment]
after copying modules directory i am able to execute further but facing new issue 


                 _
     _ __  _   _| |___  __ _ _ __
    | '_ \| | | | / __|/ _` | '__|
    | |_) | |_| | \__ \ (_| | |
    | .__/ \__,_|_|___/\__,_|_|  v0.1-dev
    |_|

>>> Extracting DERRICK files from tcap_fuzzing
>>> Generating PRISMA input files from tcap_fuzzing
>>> Clustering data...

R version 3.0.2 (2013-09-25) -- "Frisbee Sailing"
Copyright (C) 2013 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

>
> # reading arguments
> cmd_args<- commandArgs(TRUE)
> prisma_dir<-cmd_args[1]
> capture_dir<-cmd_args[2]
> clusters_file<-cmd_args[3]
> nmf_ncomp<-cmd_args[4]
> print(cmd_args)
[1] "modules/PRISMA/R"
[2] "/root/pulsar/models/tcap_fuzzing/tcap_fuzzing"
[3] "/root/pulsar/models/tcap_fuzzing/tcap_fuzzing.cluster"
[4] "0"
>
> # store the current directory
> initial_dir<-getwd()
>
> # load necessary libraries
> # library(PRISMA)
> library(Matrix)
>
> # change to prisma src dir and load scripts
> setwd(prisma_dir)
> source("prisma.R")
> source("dimensionEstimation.R")
> source("matrixFactorization.R")
> setwd(initial_dir)
>
> # load the dataset
> data = loadPrismaData(capture_dir)
Reading data...
Splitting ngrams...
Calc indices...
Setup matrix...
Error in subCsp_rows(x, i, drop = drop) :
  Cholmod error 'invalid rset' at file ../MatrixOps/cholmod_submatrix.c, line 209
Calls: loadPrismaData ... callGeneric -> eval -> eval -> [ -> [ -> subCsp_rows
In addition: Warning messages:
1: In sqrt(N * mu * (1 - mu)) : NaNs produced
2: In sqrt(N * mu * (1 - mu)) : NaNs produced
Execution halted
Error during clustering (not enough data?)
Cluster file not generated: /root/pulsar/models/tcap_fuzzing/tcap_fuzzing.cluster
Exiting learning module...

**Comment by hgascon** [comment]
How do you generate the pcap file? Note that it should only include the packages corresponding to a connection between a client and a server at specific ports (e.g. SRC_IP:PORT1 - DST_IP:PORT2).

**Comment by akibsayyed** [comment]
Mode of communication is UDP and only security and fest packages are there.

**Comment by hgascon** [comment]
The goal of PRISMA and Pulsar is to model the state machine of a protocol and be able to simulate the communication channel. UDP is a stateless protocol and therefore can't be modeled. You can try then with a capture of a TCP connection.
